### ISSUE TITLE
[Task] Home 화면, Navigation Bar 구현

### ISSUE THREAD

**Issue by muthwanzim** [codestates/Uristorage#10]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Client 초기화면 구현
### TODO
- [x] Home 화면 구현
- [x] Navigation Bar 구현
- [ ] Redux 상태관리 고민
