### ISSUE TITLE
[Task] words,groups CRUD완성 시키기

### ISSUE THREAD

**Issue by yonggar** [codestates/Uristorage#35]
### ISSUE
- Group: `client`, `server`
- Type:  `feature`

### TODO
- [x] 그룹 정보 변경 기능
- [x] 단어 삭제 기능
- [x] 단어 정보 변경 기능
### Estimated time
`6h`
