### ISSUE TITLE
[Task]Image 파일 업로드, words에 작성자 닉네임 정보 전달

### ISSUE THREAD

**Issue by yonggar** [codestates/Uristorage#36]
### ISSUE
- Group: `client`, `server`
- Type: `feature`

### TODO
- [x] Image 파일 업로드 기능 구현
- [x] public words, my words에 작성자 닉네임 정보 전달
- [x] group words 작성자 닉네임 정보 전달
### Estimated time
`1d`
