### ISSUE TITLE
[Task] https적용, 필터, 페이지네이션 수정

### ISSUE THREAD

**Issue by yonggar** [codestates/Uristorage#40]
### ISSUE
- Group: `client`, `server`, `sr`
- Type:`feature`

### TODO
- [x] server, client https적용
- [ ] 타입필터 기능 구현하기
- [ ] 페이지네이션 기능 구현하기
- [x] 그룹정보변경 그룹원추가 확인기능 추가

### Estimated time
`1h`
