### ISSUE TITLE
[Task] Client 틀 제작

### ISSUE THREAD

**Issue by muthwanzim** [codestates/Uristorage#5]
### ISSUE
- Group: `client`
- Type: `create`
- Detail: 초기 client 기본 구현

### TODO
- [x] html 파일 제작
- [x] Index.js 파일 제작
- [x] React를 위한 App.js 파일 제작

### Estimated time
`1h`
