### ISSUE TITLE
[Task]Prototype 제작(Home, Mypage)

### ISSUE THREAD

**Issue by yonggar** [codestates/Uristorage#6]
### ISSUE
- Group:  `sr`
- Type:  `feature`
- Detail: home,mypage 프로토타입 제작
### TODO
- [x] 김준환 home,mypage 프로토타입 제작해보기(figma사용)
- [x] 권순규 home,mypage 프로토타입 제작해보기(figma사용)
- [x] 김용진 home,mypage 프로토타입 제작해보기(figma사용)
### Estimated time
`2.5h`
