### ISSUE TITLE
[Task] Mypage 틀 제작 및 컴포넌트 구성

### ISSUE THREAD

**Issue by sooonkyu** [codestates/Uristorage#7]
### ISSUE
- Group: `client`
- Type: `create`
- Detail: Mypage 기본 제작 및 컴포넌트 구현
### TODO
- [x] MyPage 제작(+기초 css)(2h)
- [x] 프로필 컴포넌트 구현(3h)
- [ ] 필터 컴포넌트 구현(3h ~)
- [ ] Redux 공부 - 서버 데이터 주고받기
### Estimated time
> Pick one
`1d`
